In [ ]:
 ''' #String Function 
---------------
1. replace -> 
2. strip(), LStrip(), RStrip() -> remove white strip, left & right

'''

In [4]:
import pandas as pd

In [6]:
df = pd.read_csv('Dataset/HR_Dataset Refresh.csv')
df.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 582 entries, 0 to 581
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_Name               582 non-null    object
 1   EmpID                       582 non-null    int64
 2   MarriedID                   582 non-null    int64
 3   MaritalStatusID             582 non-null    int64
 4   GenderID                    582 non-null    int64
 5   EmpStatusID                 582 non-null    int64
 6   DeptID                      582 non-null    int64
 7   PerfScoreID                 582 non-null    int64
 8   FromDiversityJobFairID      582 non-null    int64
 9   Salary                      582 non-null    int64
 10  Termd                       582 non-null    int64
 11  PositionID                  582 non-null    int64
 12  Position                    582 non-null    object
 13  State                       582 non-null    object
 14  Zip                         582 non-null    int64
 15  DOB                         582 non-null    object
 16  Gender                      582 non-null    object
 17  MaritalDesc                 582 non-null    object
 18  CitizenDesc                 582 non-null    object
 19  HispanicLatino              582 non-null    object
 20  RaceDesc                    582 non-null    object
 21  DateofHire                  582 non-null    object
 22  DateofTermination           196 non-null    object
 23  TermReason                  582 non-null    object
 24  EmploymentStatus            582 non-null    object
 25  Department                  582 non-null    object
 26  ManagerName                 582 non-null    object
 27  ManagerID                   574 non-null    float64
 28  RecruitmentSource           582 non-null    object
 29  PerformanceScore            582 non-null    object
 30  EngagementSurvey            582 non-null    float64
 31  EmpSatisfaction             582 non-null    int64
 32  SpecialProjectsCount        582 non-null    int64
 33  LastPerformanceReview_Date  582 non-null    object
 34  DaysLateLast30              582 non-null    int64
 35  Absences                    582 non-null    int64
dtypes: float64(2), int64(16), object(18)
memory usage: 163.8+ KB

In [10]:
categorical_columns = df.select_dtypes(include=['object']).columns
categorical_columns

Index(['Employee_Name', 'Position', 'State', 'DOB', 'Gender', 'MaritalDesc',
       'CitizenDesc', 'HispanicLatino', 'RaceDesc', 'DateofHire',
       'DateofTermination', 'TermReason', 'EmploymentStatus', 'Department',
       'ManagerName', 'RecruitmentSource', 'PerformanceScore',
       'LastPerformanceReview_Date'],
      dtype='object')

In [72]:
columns= ['Position', 'State', 'Gender', 'MaritalDesc',
       'CitizenDesc', 'HispanicLatino', 'RaceDesc',
        'TermReason', 'EmploymentStatus', 'Department',
       'ManagerName', 'RecruitmentSource', 'PerformanceScore',
       'LastPerformanceReview_Date']
for col in columns:
    unique = df[col].unique()
    print(col)
    print('--'*35)
    print(unique)
    print("\n")

Position
----------------------------------------------------------------------
['Production Technician I' 'Sr. DBA' 'Production Technician II'
 'Software Engineer' 'IT Support' 'Data Analyst' 'Database Administrator'
 'Enterprise Architect' 'Sr. Accountant' 'Production Manager'
 'Accountant I' 'Area Sales Manager' 'Software Engineering Manager'
 'BI Director' 'Director of Operations' 'Sr. Network Engineer'
 'Sales Manager' 'BI Developer' 'IT Manager - Support' 'Network Engineer'
 'IT Director' 'Director of Sales' 'Administrative Assistant'
 'President & CEO' 'Senior BI Developer' 'Shared Services Manager'
 'IT Manager - Infra' 'Principal Data Architect' 'Data Architect'
 'IT Manager - DB' 'CIO']


State
----------------------------------------------------------------------
['MA' 'TX' 'CT' 'VA' 'VT' 'AL' 'WA' 'CA' 'OH' 'IN' 'TN' 'NH' 'RI' 'PA'
 'CO' 'NY' 'UT' 'GA' 'FL' 'NC' 'KY' 'ID' 'NV' 'MT' 'OR' 'ND' 'AZ' 'ME']


Gender
----------------------------------------------------------------------
['M' 'F']


MaritalDesc
----------------------------------------------------------------------
['Single' 'Married' 'Divorced' 'Widowed' 'Separated']


CitizenDesc
----------------------------------------------------------------------
['US Citizen' 'Eligible NonCitizen' 'Non-Citizen']


HispanicLatino
----------------------------------------------------------------------
[nan]


RaceDesc
----------------------------------------------------------------------
['White' 'Black or African American' 'Two or more races' 'Asian'
 'American Indian or Alaska Native' 'Hispanic']


TermReason
----------------------------------------------------------------------
['N/A-StillEmployed' 'career change' 'hours' 'return to school'
 'Another position' 'unhappy' 'attendance' 'performance'
 'Learned that he is a gangster' 'retiring' 'relocation out of area'
 'more money' 'military' 'no-call, no-show' 'Fatal attraction'
 'maternity leave - did not return' 'medical issues' 'gross misconduct']


EmploymentStatus
----------------------------------------------------------------------
['Active' 'Voluntarily Terminated' 'Terminated for Cause']


Department
----------------------------------------------------------------------
['Production' 'IT/IS' 'Software Engineering' 'Admin Offices' 'Sales'
 'Executive Office']


ManagerName
----------------------------------------------------------------------
['Michael Albert' 'Simon Roup' 'Kissy Sullivan' 'Elijiah Gray'
 'Webster Butler' 'Amy Dunn' 'Alex Sweetwater' 'Ketsia Liebig'
 'Brannon Miller' 'Peter Monroe' 'David Stanley' 'Kelley Spirea'
 'Brandon R. LeBlanc' 'Janet King' 'John Smith' 'Jennifer Zamora'
 'Lynn Daneault' 'Eric Dougall' 'Debra Houlihan' 'Brian Champaigne'
 'Board of Directors']


RecruitmentSource
----------------------------------------------------------------------
['LinkedIn' 'Indeed' 'Google Search' 'Employee Referral'
 'Diversity Job Fair' 'On-line Web application' 'CareerBuilder' 'Website'
 'Other']


PerformanceScore
----------------------------------------------------------------------
['Exceeds' 'Fully Meets' 'Needs Improvement' 'PIP']


LastPerformanceReview_Date
----------------------------------------------------------------------
['1/17/2019' '2/24/2016' '5/15/2012' '1/3/2019' '2/1/2016' '1/7/2019'
 '1/2/2019' '2/25/2019' '1/25/2019' '2/18/2019' '1/30/2016' '5/6/2016'
 '2/14/2019' '3/2/2017' '4/5/2017' '1/14/2019' '1/15/2015' '1/11/2019'
 '1/10/2019' '2/27/2019' '3/4/2014' '1/10/2016' '2/20/2014' '3/4/2013'
 '1/15/2019' '2/1/2019' '1/21/2019' '2/10/2013' '2/21/2019' '2/22/2019'
 '1/30/2019' '2/12/2019' '2/19/2019' '1/19/2019' '3/10/2015' '5/3/2012'
 '5/4/2011' '2/28/2019' '5/1/2016' '2/4/2019' '1/22/2019' '1/28/2019'
 '1/24/2019' '1/31/2019' '4/2/2016' '5/6/2015' '1/23/2019' '1/29/2019'
 '1/18/2019' '1/4/2019' '1/27/2019' '4/9/2017' '2/13/2019' '4/12/2018'
 '1/15/2017' '8/10/2012' '2/4/2016' '4/5/2013' '1/7/2012' '2/8/2019'
 '2/26/2019' '1/16/2019' '4/29/2016' '1/15/2014' '1/20/2015' '2/7/2019'
 '3/6/2011' '2/15/2019' '6/3/2013' '2/1/2013' '1/8/2019' '5/2/2015'
 '2/11/2019' '1/30/2013' '3/5/2012' '4/15/2015' '4/12/2012' '2/14/2018'
 '2/3/2016' '3/30/2013' '3/1/2015' '2/6/2019' '2/15/2015' '2/20/2013'
 '7/2/2017' '3/2/2018' '6/10/2016' '2/2/2015' '4/1/2017' '7/2/2012'
 '2/5/2016' '1/14/2013' '3/2/2013' '3/6/2016' '3/9/2018' '7/2/2013'
 '8/16/2015' '1/16/2016' '4/6/2017' '2/6/2015' '5/13/2014' '1/10/2013'
 '3/5/2015' '2/20/2012' '4/2/2018' '4/2/2013' '4/19/2014' '2/4/2018'
 '3/30/2015' '10/22/2011' '1/6/2012' '1/10/2015' '4/5/2016' '2/13/2018'
 '7/2/2018' '1/4/2015' '2/5/2018' '4/20/2015' '4/2/2015' '8/15/2013'
 '3/2/2015' '2/15/2012' '4/18/2017' '3/2/2016' '7/14/2010' '2/12/2017'
 '1/5/2014' '2/15/2017' '2/1/2015' '1/2/2012' '9/5/2014' '2/5/2019'
 '5/15/2014' '2/6/2011' '6/2/2014' '1/19/2016' '9/2/2015']

In [74]:
#String Func

In [76]:
#Strip() -> Used to remove unnecessary data like white spaces
df['Position']=df['Position'].str.strip()

In [78]:
df['Gender']=df['Gender'].str.strip()

In [80]:
#Removing all white spaces using for loop so that everything gets cleared at once.
columns= ['Position', 'State', 'Gender', 'MaritalDesc',
       'CitizenDesc', 'HispanicLatino', 'RaceDesc',
        'TermReason', 'EmploymentStatus', 'Department',
       'ManagerName', 'RecruitmentSource', 'PerformanceScore',
       'LastPerformanceReview_Date']
for s_col in columns:
    df[s_col]= df[s_col].str.strip()

In [82]:
#To clean double yes no acceptance
df['HispanicLatino'].unique()

array([nan], dtype=object)

In [84]:
#df['HispanicLatino']=df['HispanicLatino'].str.upper()

In [86]:
h1 = {
    'no':'No',
    'yes':'Yes',
    'Yes':'Yes',
    'No':  'No'
    
}
df['HispanicLatino']=df['HispanicLatino'].map(h1)

In [ ]:
#Removing commas from Employee Name

In [89]:
df

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2
578,"Anderson, Linda",10002,0,0,0,1,5,4,0,57568,...,Amy Dunn,11.0,LinkedIn,Exceeds,5.00,5,0,1/7/2019,0,15
579,"Andreola, Colby",10194,0,0,0,1,4,3,0,95660,...,Alex Sweetwater,10.0,LinkedIn,Fully Meets,3.04,3,4,1/2/2019,0,19
580,"Athwal, Sam",10062,0,4,1,1,5,3,0,59365,...,Ketsia Liebig,19.0,Employee Referral,Fully Meets,5.00,4,0,2/25/2019,0,19
581,"Bachiochi, Linda",10114,0,0,0,3,5,3,1,47837,...,Brannon Miller,12.0,Diversity Job Fair,Fully Meets,4.46,3,0,1/25/2019,0,4

In [ ]:
#Replace(find, replace_value,regex= True(default)/false)

In [93]:
df['Employee_Name'] = df['Employee_Name'].str.replace(',', '',regex=False)
df

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,AlagbeTrina,10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2
578,Anderson Linda,10002,0,0,0,1,5,4,0,57568,...,Amy Dunn,11.0,LinkedIn,Exceeds,5.00,5,0,1/7/2019,0,15
579,Andreola Colby,10194,0,0,0,1,4,3,0,95660,...,Alex Sweetwater,10.0,LinkedIn,Fully Meets,3.04,3,4,1/2/2019,0,19
580,Athwal Sam,10062,0,4,1,1,5,3,0,59365,...,Ketsia Liebig,19.0,Employee Referral,Fully Meets,5.00,4,0,2/25/2019,0,19
581,Bachiochi Linda,10114,0,0,0,3,5,3,1,47837,...,Brannon Miller,12.0,Diversity Job Fair,Fully Meets,4.46,3,0,1/25/2019,0,4

In [ ]:
''' 
DateTime
-----------------
to_datetime()

format
-------
1. %d.%m.%y
2. %d-%m-%y
3. mixed 
---------------- 
dayfirst = False(default)/True
-----------
After Convert
----------------
year-month-day

---------------------

'''

In [95]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 582 entries, 0 to 581
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_Name               582 non-null    object
 1   EmpID                       582 non-null    int64
 2   MarriedID                   582 non-null    int64
 3   MaritalStatusID             582 non-null    int64
 4   GenderID                    582 non-null    int64
 5   EmpStatusID                 582 non-null    int64
 6   DeptID                      582 non-null    int64
 7   PerfScoreID                 582 non-null    int64
 8   FromDiversityJobFairID      582 non-null    int64
 9   Salary                      582 non-null    int64
 10  Termd                       582 non-null    int64
 11  PositionID                  582 non-null    int64
 12  Position                    582 non-null    object
 13  State                       582 non-null    object
 14  Zip                         582 non-null    int64
 15  DOB                         582 non-null    object
 16  Gender                      582 non-null    object
 17  MaritalDesc                 582 non-null    object
 18  CitizenDesc                 582 non-null    object
 19  HispanicLatino              0 non-null      object
 20  RaceDesc                    582 non-null    object
 21  DateofHire                  582 non-null    object
 22  DateofTermination           196 non-null    object
 23  TermReason                  582 non-null    object
 24  EmploymentStatus            582 non-null    object
 25  Department                  582 non-null    object
 26  ManagerName                 582 non-null    object
 27  ManagerID                   574 non-null    float64
 28  RecruitmentSource           582 non-null    object
 29  PerformanceScore            582 non-null    object
 30  EngagementSurvey            582 non-null    float64
 31  EmpSatisfaction             582 non-null    int64
 32  SpecialProjectsCount        582 non-null    int64
 33  LastPerformanceReview_Date  582 non-null    object
 34  DaysLateLast30              582 non-null    int64
 35  Absences                    582 non-null    int64
dtypes: float64(2), int64(16), object(18)
memory usage: 163.8+ KB

In [101]:
df['DOB '] = pd.to_datetime(df['DOB'])
df['DOB']

0      7/10/1983
1       5/5/1975
2      9/19/1988
3      9/27/1988
4       9/8/1989
         ...
577     9/8/1989
578    5/22/1977
579    5/24/1979
580    2/18/1983
581    2/11/1970
Name: DOB, Length: 582, dtype: object

In [129]:
#df['DOB'] = pd.to_datetime(df['DOB'], format= mixed)
#df['DOB']

NameError: name 'mixed' is not defined

In [118]:
df['DateofTermination']= pd.to_datetime(df['DateofTermination'])
df['DateofTermination']

0            NaT
1     2016-06-16
2     2012-09-24
3            NaT
4     2016-09-06
         ...
577   2016-09-06
578          NaT
579          NaT
580          NaT
581          NaT
Name: DateofTermination, Length: 582, dtype: datetime64[ns]

In [120]:
df['DateofHire']= pd.to_datetime(df['DateofHire'])

In [122]:
 mgr_mode=df['ManagerID'].mode()[0]
df['ManagerID']= df['ManagerID'].fillna(mgr_mode)

In [124]:
 df['ManagerID']=  df['ManagerID'].astype(int)

In [126]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 582 entries, 0 to 581
Data columns (total 37 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_Name               582 non-null    object
 1   EmpID                       582 non-null    int64
 2   MarriedID                   582 non-null    int64
 3   MaritalStatusID             582 non-null    int64
 4   GenderID                    582 non-null    int64
 5   EmpStatusID                 582 non-null    int64
 6   DeptID                      582 non-null    int64
 7   PerfScoreID                 582 non-null    int64
 8   FromDiversityJobFairID      582 non-null    int64
 9   Salary                      582 non-null    int64
 10  Termd                       582 non-null    int64
 11  PositionID                  582 non-null    int64
 12  Position                    582 non-null    object
 13  State                       582 non-null    object
 14  Zip                         582 non-null    int64
 15  DOB                         582 non-null    object
 16  Gender                      582 non-null    object
 17  MaritalDesc                 582 non-null    object
 18  CitizenDesc                 582 non-null    object
 19  HispanicLatino              0 non-null      object
 20  RaceDesc                    582 non-null    object
 21  DateofHire                  582 non-null    datetime64[ns]
 22  DateofTermination           196 non-null    datetime64[ns]
 23  TermReason                  582 non-null    object
 24  EmploymentStatus            582 non-null    object
 25  Department                  582 non-null    object
 26  ManagerName                 582 non-null    object
 27  ManagerID                   582 non-null    int32
 28  RecruitmentSource           582 non-null    object
 29  PerformanceScore            582 non-null    object
 30  EngagementSurvey            582 non-null    float64
 31  EmpSatisfaction             582 non-null    int64
 32  SpecialProjectsCount        582 non-null    int64
 33  LastPerformanceReview_Date  582 non-null    object
 34  DaysLateLast30              582 non-null    int64
 35  Absences                    582 non-null    int64
 36  DOB                         582 non-null    datetime64[ns]
dtypes: datetime64[ns](3), float64(1), int32(1), int64(16), object(16)
memory usage: 166.1+ KB