In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Dataset/Employees.csv')
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0

In [3]:
df['COMMISSION_PCT']=df['COMMISSION_PCT'].fillna(0.22)
df['MANAGER_ID']=df['MANAGER_ID'].fillna(100.0)
df['DEPARTMENT_ID']=df['DEPARTMENT_ID'].fillna(50.0)

In [4]:
df['MANAGER_ID']=df['MANAGER_ID'].astype(int)
df['DEPARTMENT_ID']=df['DEPARTMENT_ID'].astype(int)

In [5]:
df['HIRE_DATE']= pd.to_datetime(df['HIRE_DATE'])

In [6]:
''' 
GROUPBY()
AGGREGRATE func()
  1. mean()
  2. max()
  3. min()
  4. count()
  5. sum()

'''

' \nGROUPBY()\nAGGREGRATE func()\n  1. mean()\n  2. max()\n  3. min()\n  4. count()\n  5. sum()\n\n'

In [7]:
#If you use groupby then aggregrate func must be used 
#If one uses aggregrate func then groupby clause is not mandatory

In [8]:
#variable = df.groupby(column1)[column2].count()

In [9]:
#variable = df.groupby(column1)

In [10]:
#Find total employees working in each departemt

In [11]:
#For formatting use // reset_index()
emp_dep = df.groupby('DEPARTMENT_ID')['EMPLOYEE_ID'].count().reset_index()
emp_dep

    DEPARTMENT_ID  EMPLOYEE_ID
0              10            1
1              20            2
2              30            6
3              40            2
4              50           46
5              60            5
6              70            2
7              80           34
8              90            3
9             100            6
10            110            4

In [12]:
#Formatting using markdown
emp_dep = df.groupby('DEPARTMENT_ID')['EMPLOYEE_ID'].count()

format_data = emp_dep.to_markdown(stralign='center', numalign= 'center')
print(format_data)

|  DEPARTMENT_ID  |  EMPLOYEE_ID  |
|:---------------:|:-------------:|
|       10        |       1       |
|       20        |       2       |
|       30        |       6       |
|       40        |       2       |
|       50        |      46       |
|       60        |       5       |
|       70        |       2       |
|       80        |      34       |
|       90        |       3       |
|       100       |       6       |
|       110       |       4       |

In [13]:
emp_dep = df.groupby('DEPARTMENT_ID')['EMPLOYEE_ID'].count().reset_index().rename(columns= {
     'EMPLOYEE_ID':'Count of employees', 'DEPARTMENT_ID':'Departments'
    
})

emp_dep

    Departments  Count of employees
0            10                   1
1            20                   2
2            30                   6
3            40                   2
4            50                  46
5            60                   5
6            70                   2
7            80                  34
8            90                   3
9           100                   6
10          110                   4

In [14]:
emp_dep = (
    df.groupby('DEPARTMENT_ID')['EMPLOYEE_ID']
      .count()
      .reset_index()
      .rename(columns={
          'EMPLOYEE_ID': 'Count of employees',
          'DEPARTMENT_ID': 'Departments'
      })
      .sort_values(by='Count of employees', ascending=True,ignore_index=True)#Professionally used otherwise use reset= True
)
emp_dep

    Departments  Count of employees
0            10                   1
1            20                   2
2            40                   2
3            70                   2
4            90                   3
5           110                   4
6            60                   5
7            30                   6
8           100                   6
9            80                  34
10           50                  46

In [15]:
#Fix index 
1. Check department total salary
2. job wise total employess

SyntaxError: invalid syntax (1158046774.py, line 2)

In [ ]:
job_emp = df.groupby('JOB_ID')['EMPLOYEE_ID'].count().reset_index().rename(columns= {'JOB_ID':'Job_Name','EMPLOYEE_ID':'Count of employee'})

In [ ]:
job_filter= job_emp['Count of employee'] > 2
job_emp[job_filter]

In [ ]:
total_salary=df.groupby('DEPARTMENT_ID')['SALARY'].sum().reset_index().rename(columns = {'DEPARTMENT_ID':'Member of department','SALARY':'Salary'}).sort_values(ascending= False, by = 'Salary', ignore_index= True)

In [ ]:
total_salary.head()

In [ ]:
dep_job = (
    df.groupby(['DEPARTMENT_ID', 'JOB_ID'])['SALARY']
      .sum()
      .reset_index()
      .rename(columns={'DEPARTMENT_ID': 'dept', 'JOB_ID': 'job'})
)
dep_job

In [ ]:
dep_job_report = (
    df.groupby(['DEPARTMENT_ID', 'JOB_ID'])
      .agg(Total_Salary=('SALARY', 'sum'))
      .reset_index()
)

print(dep_job_report)

In [ ]:
dep_job_report['Total_Salary'] = dep_job_report['Total_Salary'].map("Rs.{:,.2f}".format)
dep_job_report

In [ ]:
columns = ['Max_Salary', 'Min_Salary', 'Avg Salary']

for col in columns:
    dep_job_report[col] = dep_job_report[col].map("Rs.{:,.2f}".format)

In [25]:
dep_job_report.style.set_table_styles([
    {
        'selector': 'th',
        'props': [('text-align', 'center')]
    },
    {
        'selector': 'td',
        'props': [('text-align', 'center')]
    }
])

NameError: name 'dep_job_report' is not defined

In [27]:
Date Time
--------
Time Intelligence Function

MoM-> Month Over Month Growth
YoY->Year Over Year Growth

PMTD -> Previous Month to Date
PYTD -> Previous Year to Date

CMTD -> Current Month to Date
CYTD -> Current Year to Date

SyntaxError: invalid syntax (647556567.py, line 1)

In [29]:
df['HIRE_DATE']= pd.to_datetime(df['HIRE_DATE'])

In [31]:
df['HIRE_DATE'] = pd.to_datetime(df['HIRE_DATE'])

df['HIRE_YEAR'] = df['HIRE_DATE'].dt.year
df['HIRE_MONTH'] = df['HIRE_DATE'].dt.month_name()
df['HIRE_DAY'] = df['HIRE_DATE'].dt.day_name()

In [33]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID,HIRE_YEAR,HIRE_MONTH,HIRE_DAY
0,100,Steven,King,SKING,515.123.4567,2003-06-17,AD_PRES,24000,0.22,100,90,2003,June,Tuesday
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,2005-09-21,AD_VP,17000,0.22,100,90,2005,September,Wednesday
2,102,Lex,De Haan,LDEHAAN,515.123.4569,2001-01-13,AD_VP,17000,0.22,100,90,2001,January,Saturday
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,2006-01-03,IT_PROG,9000,0.22,102,60,2006,January,Tuesday
4,104,Bruce,Ernst,BERNST,590.423.4568,2007-05-21,IT_PROG,6000,0.22,103,60,2007,May,Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,2002-06-07,AC_ACCOUNT,8300,0.22,205,110,2002,June,Friday
107,203,Susan,Mavris,SMAVRIS,515.123.7777,2002-06-07,HR_REP,6500,0.22,101,40,2002,June,Friday
108,204,Hermann,Baer,HBAER,515.123.8888,2002-06-07,PR_REP,10000,0.22,101,70,2002,June,Friday
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,2002-06-07,AC_MGR,12008,0.22,101,110,2002,June,Friday
110,206,William,Gietz,WGIETZ,515.123.8181,2002-06-07,AC_ACCOUNT,8300,0.22,205,110,2002,June,Friday

In [35]:
''' 
1. Find total employees hired in each day.
2. Find total employees hired in each month.
'''

' \n1. Find total employees hired in each day.\n2. Find total employees hired in each month.\n'

In [37]:
weekdays=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']
df['HIRE_DAY']= pd.Categorical(df['HIRE_DAY'],categories = weekdays)

In [39]:
emp_day = df.groupby(df['HIRE_DAY'], observed= False)['EMPLOYEE_ID'].count().reset_index()
emp_day

    HIRE_DAY  EMPLOYEE_ID
0     Sunday           15
1     Monday           10
2    Tuesday           13
3  Wednesday           15
4   Thursday           16
5     Friday           23
6   Saturday           19

In [41]:
df['HIRE_MONTH_NUM']=df['HIRE_DATE'].dt.month

In [43]:
month_emp= df.groupby(['HIRE_MONTH','HIRE_MONTH_NUM'])['EMPLOYEE_ID'].count().reset_index()
month_emp

   HIRE_MONTH  HIRE_MONTH_NUM  EMPLOYEE_ID
0       April               4            7
1      August               8            9
2    December              12            7
3    February               2           13
4     January               1           14
5        July               7            7
6        June               6           15
7       March               3           17
8         May               5            6
9    November              11            5
10    October              10            6
11  September               9            5

In [45]:
month_emp= df.groupby(['HIRE_MONTH_NUM','HIRE_MONTH'])['EMPLOYEE_ID'].count().reset_index()
month_emp

    HIRE_MONTH_NUM HIRE_MONTH  EMPLOYEE_ID
0                1    January           14
1                2   February           13
2                3      March           17
3                4      April            7
4                5        May            6
5                6       June           15
6                7       July            7
7                8     August            9
8                9  September            5
9               10    October            6
10              11   November            5
11              12   December            7

In [63]:
month_emp = df.groupby(['HIRE_MONTH_NUM', 'HIRE_MONTH']).agg(
    Total_Employees=('EMPLOYEE_ID', 'count')
).reset_index()

month_data = month_emp[['HIRE_MONTH', 'Total_Employees']]

In [65]:
df['HIRE_YEAR'].unique()

array([2003, 2005, 2001, 2006, 2007, 2002, 2004, 2008])

In [67]:
year_data=df.groupby('HIRE_YEAR').count().reset_index()

cmtd = (year_data['Hire_YEAR']==2008)
year_data[smtd]

In [71]:
pmtd = (year_data['HIRE_YEAR'] == 2007)

pmtd_data = year_data[pmtd]

pmtd_data

,HIRE_YEAR,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID,HIRE_MONTH,HIRE_DAY,HIRE_MONTH_NUM
6,2007,19,19,19,19,19,19,19,19,19,19,19,19,19,19

In [73]:
cmtd = (year_data['HIRE_YEAR'] == 2007)

cmtd_data = year_data[cmtd]

cmtd_data

,HIRE_YEAR,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID,HIRE_MONTH,HIRE_DAY,HIRE_MONTH_NUM
6,2007,19,19,19,19,19,19,19,19,19,19,19,19,19,19

In [75]:
year_data = df.groupby('HIRE_YEAR')['EMPLOYEE_ID'].count().reset_index()

In [77]:
year_data['YoY_Growth']=year_data['EMPLOYEE_ID'].pct_change()

In [81]:
year_data['YoY%'] = year_data['YoY_Growth']*100

In [87]:
month_data['MoM_Growth']=month_data['Total_Employees'].pct_change()
month_data['YoY%'] = month_data['MoM_Growth']*100

In [ ]:
#(current_date - previous_date)/ total_number_of_data