In [3]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('Dataset/Employees.csv')
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0

In [7]:
df.shape

(111, 11)

In [9]:
df.columns

Index(['EMPLOYEE_ID', 'FIRST_NAME', 'LAST_NAME', 'EMAIL', 'PHONE_NUMBER',
       'HIRE_DATE', 'JOB_ID', 'SALARY', 'COMMISSION_PCT', 'MANAGER_ID',
       'DEPARTMENT_ID'],
      dtype='object')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EMPLOYEE_ID     111 non-null    int64
 1   FIRST_NAME      111 non-null    object
 2   LAST_NAME       111 non-null    object
 3   EMAIL           111 non-null    object
 4   PHONE_NUMBER    111 non-null    object
 5   HIRE_DATE       111 non-null    object
 6   JOB_ID          111 non-null    object
 7   SALARY          111 non-null    int64
 8   COMMISSION_PCT  35 non-null     float64
 9   MANAGER_ID      110 non-null    float64
 10  DEPARTMENT_ID   110 non-null    float64
dtypes: float64(3), int64(2), object(6)
memory usage: 9.7+ KB

In [13]:
df.describe()

       EMPLOYEE_ID        SALARY  COMMISSION_PCT  MANAGER_ID  DEPARTMENT_ID
count   111.000000    111.000000       35.000000  110.000000     110.000000
mean    154.855856   6560.576577        0.222857  124.845455      63.909091
std      31.953047   3891.443849        0.085184   21.729440      21.592364
min     100.000000   2100.000000        0.100000  100.000000      10.000000
25%     127.500000   3100.000000        0.150000  108.000000      50.000000
50%     155.000000   6400.000000        0.200000  122.000000      50.000000
75%     182.500000   9000.000000        0.300000  145.000000      80.000000
max     206.000000  24000.000000        0.400000  205.000000     110.000000

In [15]:
df.isnull().sum()

EMPLOYEE_ID        0
FIRST_NAME         0
LAST_NAME          0
EMAIL              0
PHONE_NUMBER       0
HIRE_DATE          0
JOB_ID             0
SALARY             0
COMMISSION_PCT    76
MANAGER_ID         1
DEPARTMENT_ID      1
dtype: int64

In [17]:
df.columns = df.columns.str.strip()

In [19]:
df.drop_duplicates(inplace=True)

In [23]:
df['SALARY'] = df['SALARY'].fillna(df['SALARY'].median())
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
102,202,Pat,Fay,PFAY,603.123.6666,8/17/2005,MK_REP,6000,NaN,201.0,20.0
103,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
104,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
105,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

In [25]:
df['DEPARTMENT_ID'] = df['DEPARTMENT_ID'].fillna(df['DEPARTMENT_ID'].median())
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
102,202,Pat,Fay,PFAY,603.123.6666,8/17/2005,MK_REP,6000,NaN,201.0,20.0
103,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
104,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
105,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

In [27]:
sorted_df = df.sort_values(by='SALARY', ascending=False)

In [29]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
102,202,Pat,Fay,PFAY,603.123.6666,8/17/2005,MK_REP,6000,NaN,201.0,20.0
103,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
104,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
105,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

In [31]:
df['SALARY'] = df['SALARY'].replace('[₹,]', '', regex=True).astype(float)

In [33]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000.0,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000.0,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000.0,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000.0,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000.0,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
102,202,Pat,Fay,PFAY,603.123.6666,8/17/2005,MK_REP,6000.0,NaN,201.0,20.0
103,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500.0,NaN,101.0,40.0
104,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000.0,NaN,101.0,70.0
105,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008.0,NaN,101.0,110.0
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300.0,NaN,205.0,110.0

In [ ]:
df['SALARY'] = df['SALARY'].fillna(df['SALARY'].median())