In [3]:
#Feature Engineering

import pandas as pd

In [5]:
df = pd.read_csv('Dataset/HR_Dataset Refresh.csv')
df.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2

In [12]:
df['Employee_Name'] = df['Employee_Name'].str.replace(',', ' ',regex=False)
df

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences,last_name,first_name,middle_name
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,Exceeds,4.60,5,0,1/17/2019,0,1,,A,dinolfi Wilson K
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,Fully Meets,4.96,3,6,2/24/2016,0,17,,A,it Sidi Karthikeyan
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,Fully Meets,3.02,3,0,5/15/2012,0,3,,A,kinkuolie Sarah
3,AlagbeTrina,10088,1,1,0,1,5,3,0,64991,...,Fully Meets,4.84,5,0,1/3/2019,0,15,,A,lagbeTrina
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,Fully Meets,5.00,4,0,2/1/2016,0,2,,A,nderson Carol
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,Fully Meets,5.00,4,0,2/1/2016,0,2,,A,nderson Carol
578,Anderson Linda,10002,0,0,0,1,5,4,0,57568,...,Exceeds,5.00,5,0,1/7/2019,0,15,,A,nderson Linda
579,Andreola Colby,10194,0,0,0,1,4,3,0,95660,...,Fully Meets,3.04,3,4,1/2/2019,0,19,,A,ndreola Colby
580,Athwal Sam,10062,0,4,1,1,5,3,0,59365,...,Fully Meets,5.00,4,0,2/25/2019,0,19,,A,thwal Sam
581,Bachiochi Linda,10114,0,0,0,3,5,3,1,47837,...,Fully Meets,4.46,3,0,1/25/2019,0,4,,B,achiochi Linda

In [14]:
#To break column use split(find value,(n) no of column= index,expand=True)

In [18]:
df[['last_name','first_name','middle_name']] = df['Employee_Name'].str.split(' ', n=2, expand = True)
df

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences,last_name,first_name,middle_name
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,Exceeds,4.60,5,0,1/17/2019,0,1,Adinolfi,Wilson,K
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,Fully Meets,4.96,3,6,2/24/2016,0,17,Ait,Sidi,Karthikeyan
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,Fully Meets,3.02,3,0,5/15/2012,0,3,Akinkuolie,Sarah,None
3,AlagbeTrina,10088,1,1,0,1,5,3,0,64991,...,Fully Meets,4.84,5,0,1/3/2019,0,15,AlagbeTrina,None,None
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,Fully Meets,5.00,4,0,2/1/2016,0,2,Anderson,Carol,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,Fully Meets,5.00,4,0,2/1/2016,0,2,Anderson,Carol,
578,Anderson Linda,10002,0,0,0,1,5,4,0,57568,...,Exceeds,5.00,5,0,1/7/2019,0,15,Anderson,Linda,
579,Andreola Colby,10194,0,0,0,1,4,3,0,95660,...,Fully Meets,3.04,3,4,1/2/2019,0,19,Andreola,Colby,None
580,Athwal Sam,10062,0,4,1,1,5,3,0,59365,...,Fully Meets,5.00,4,0,2/25/2019,0,19,Athwal,Sam,None
581,Bachiochi Linda,10114,0,0,0,3,5,3,1,47837,...,Fully Meets,4.46,3,0,1/25/2019,0,4,Bachiochi,Linda,None

In [ ]:
'''
#Fix it 
1. First Name 
2. Second Name
3. Middle Name manage the row '''