In [1]:
#Feature Engineering

import pandas as pd

In [3]:
df = pd.read_csv('Dataset/HR_Dataset Refresh.csv')
df.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2

In [5]:
df['Employee_Name'] = df['Employee_Name'].str.replace(',', ' ',regex=False)
df

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,Alagbe Trina,10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2
578,Anderson Linda,10002,0,0,0,1,5,4,0,57568,...,Amy Dunn,11.0,LinkedIn,Exceeds,5.00,5,0,1/7/2019,0,15
579,Andreola Colby,10194,0,0,0,1,4,3,0,95660,...,Alex Sweetwater,10.0,LinkedIn,Fully Meets,3.04,3,4,1/2/2019,0,19
580,Athwal Sam,10062,0,4,1,1,5,3,0,59365,...,Ketsia Liebig,19.0,Employee Referral,Fully Meets,5.00,4,0,2/25/2019,0,19
581,Bachiochi Linda,10114,0,0,0,3,5,3,1,47837,...,Brannon Miller,12.0,Diversity Job Fair,Fully Meets,4.46,3,0,1/25/2019,0,4

In [7]:
#To break column use split(find value,(n) no of column= index,expand=True)

In [9]:
df[['last_name','first_name','middle_name']] = df['Employee_Name'].str.split(' ', n=2, expand = True)
df

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences,last_name,first_name,middle_name
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,Exceeds,4.60,5,0,1/17/2019,0,1,Adinolfi,,Wilson K
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,Fully Meets,4.96,3,6,2/24/2016,0,17,Ait,Sidi,Karthikeyan
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,Fully Meets,3.02,3,0,5/15/2012,0,3,Akinkuolie,,Sarah
3,Alagbe Trina,10088,1,1,0,1,5,3,0,64991,...,Fully Meets,4.84,5,0,1/3/2019,0,15,Alagbe,Trina,None
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,Fully Meets,5.00,4,0,2/1/2016,0,2,Anderson,,Carol
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,Fully Meets,5.00,4,0,2/1/2016,0,2,Anderson,,Carol
578,Anderson Linda,10002,0,0,0,1,5,4,0,57568,...,Exceeds,5.00,5,0,1/7/2019,0,15,Anderson,,Linda
579,Andreola Colby,10194,0,0,0,1,4,3,0,95660,...,Fully Meets,3.04,3,4,1/2/2019,0,19,Andreola,,Colby
580,Athwal Sam,10062,0,4,1,1,5,3,0,59365,...,Fully Meets,5.00,4,0,2/25/2019,0,19,Athwal,,Sam
581,Bachiochi Linda,10114,0,0,0,3,5,3,1,47837,...,Fully Meets,4.46,3,0,1/25/2019,0,4,Bachiochi,,Linda

In [11]:
'''
#Fix it (How to make column in this pattern along side the names to be separated in the similar order. )
1. First Name 
2. Second Name
3. Middle Name manage the row '''

'\n#Fix it (How to make column in this pattern along side the names to be separated in the similar order. )\n1. First Name \n2. Second Name\n3. Middle Name manage the row '

In [13]:
df['PerformanceScore'].unique()

array(['Exceeds', 'Fully Meets', 'Needs Improvement', 'PIP'], dtype=object)

In [15]:
ps ={
    'PIP': 0,
    'Needs Improvement': 1,
    'Fully Meets': 2,
    'Exceeds': 3
}
df['PerformanceScore_ID'] = df['PerformanceScore'].map(ps)

In [34]:
df

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences,last_name,first_name,middle_name,PerformanceScore_ID
0,Adinolfi Wilson K,10026,0,0,1,1,5,NaN,0,62506,...,4.60,5,0,1/17/2019,0,1,Adinolfi,Wilson,K,NaN
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,NaN,0,104437,...,4.96,3,6,2/24/2016,0,17,Ait,Sidi,Karthikeyan,NaN
2,Akinkuolie Sarah,10196,1,1,0,5,5,NaN,0,64955,...,3.02,3,0,5/15/2012,0,3,Akinkuolie,Sarah,None,NaN
3,AlagbeTrina,10088,1,1,0,1,5,NaN,0,64991,...,4.84,5,0,1/3/2019,0,15,AlagbeTrina,None,None,NaN
4,Anderson Carol,10069,0,2,0,5,5,NaN,0,50825,...,5.00,4,0,2/1/2016,0,2,Anderson,Carol,,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,Anderson Carol,10069,0,2,0,5,5,NaN,0,50825,...,5.00,4,0,2/1/2016,0,2,Anderson,Carol,,NaN
578,Anderson Linda,10002,0,0,0,1,5,NaN,0,57568,...,5.00,5,0,1/7/2019,0,15,Anderson,Linda,,NaN
579,Andreola Colby,10194,0,0,0,1,4,NaN,0,95660,...,3.04,3,4,1/2/2019,0,19,Andreola,Colby,None,NaN
580,Athwal Sam,10062,0,4,1,1,5,NaN,0,59365,...,5.00,4,0,2/25/2019,0,19,Athwal,Sam,None,NaN
581,Bachiochi Linda,10114,0,0,0,3,5,NaN,1,47837,...,4.46,3,0,1/25/2019,0,4,Bachiochi,Linda,None,NaN

In [28]:
first_last=df['Employee_Name'].str.split(' ', n=1, expand=True)
first_last

              0                     1
0      Adinolfi             Wilson  K
1           Ait  Sidi  Karthikeyan
2    Akinkuolie                 Sarah
3        Alagbe                 Trina
4      Anderson                Carol
..          ...                   ...
577    Anderson                Carol
578    Anderson               Linda
579    Andreola                 Colby
580      Athwal                   Sam
581   Bachiochi                 Linda

[582 rows x 2 columns]

In [30]:
first_middle= first_last[1].str.strip().str.split(
    ' ', n=1, expand=True
)
first_middle

          0             1
0    Wilson             K
1      Sidi   Karthikeyan
2     Sarah          None
3     Trina          None
4     Carol          None
..      ...           ...
577   Carol          None
578   Linda          None
579   Colby          None
580     Sam          None
581   Linda          None

[582 rows x 2 columns]

In [32]:
df['first_name']=first_middle[0]
df['middle_name']=first_middle[1]
df['last_name']=first_last[0]

In [34]:
df

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences,last_name,first_name,middle_name,PerformanceScore_ID
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,4.60,5,0,1/17/2019,0,1,Adinolfi,Wilson,K,3
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,4.96,3,6,2/24/2016,0,17,Ait,Sidi,Karthikeyan,2
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,3.02,3,0,5/15/2012,0,3,Akinkuolie,Sarah,None,2
3,Alagbe Trina,10088,1,1,0,1,5,3,0,64991,...,4.84,5,0,1/3/2019,0,15,Alagbe,Trina,None,2
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,5.00,4,0,2/1/2016,0,2,Anderson,Carol,None,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,5.00,4,0,2/1/2016,0,2,Anderson,Carol,None,2
578,Anderson Linda,10002,0,0,0,1,5,4,0,57568,...,5.00,5,0,1/7/2019,0,15,Anderson,Linda,None,3
579,Andreola Colby,10194,0,0,0,1,4,3,0,95660,...,3.04,3,4,1/2/2019,0,19,Andreola,Colby,None,2
580,Athwal Sam,10062,0,4,1,1,5,3,0,59365,...,5.00,4,0,2/25/2019,0,19,Athwal,Sam,None,2
581,Bachiochi Linda,10114,0,0,0,3,5,3,1,47837,...,4.46,3,0,1/25/2019,0,4,Bachiochi,Linda,None,2

In [36]:
#Change in date

df['DateofHire'] = pd.to_datetime(df['DateofHire'], format='mixed')

In [38]:
#Hired Year// Extracting Year
df['Hired_Year'] = df['DateofHire'].dt.year

In [40]:
df

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences,last_name,first_name,middle_name,PerformanceScore_ID,Hired_Year
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,5,0,1/17/2019,0,1,Adinolfi,Wilson,K,3,2011
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,3,6,2/24/2016,0,17,Ait,Sidi,Karthikeyan,2,2015
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,3,0,5/15/2012,0,3,Akinkuolie,Sarah,None,2,2011
3,Alagbe Trina,10088,1,1,0,1,5,3,0,64991,...,5,0,1/3/2019,0,15,Alagbe,Trina,None,2,2008
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,4,0,2/1/2016,0,2,Anderson,Carol,None,2,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,4,0,2/1/2016,0,2,Anderson,Carol,None,2,2011
578,Anderson Linda,10002,0,0,0,1,5,4,0,57568,...,5,0,1/7/2019,0,15,Anderson,Linda,None,3,2012
579,Andreola Colby,10194,0,0,0,1,4,3,0,95660,...,3,4,1/2/2019,0,19,Andreola,Colby,None,2,2014
580,Athwal Sam,10062,0,4,1,1,5,3,0,59365,...,4,0,2/25/2019,0,19,Athwal,Sam,None,2,2013
581,Bachiochi Linda,10114,0,0,0,3,5,3,1,47837,...,3,0,1/25/2019,0,4,Bachiochi,Linda,None,2,2009

In [42]:
#Extracting month
df['Hired_Month'] = df['DateofHire'].dt.month

In [44]:
df

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences,last_name,first_name,middle_name,PerformanceScore_ID,Hired_Year,Hired_Month
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,0,1/17/2019,0,1,Adinolfi,Wilson,K,3,2011,7
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,6,2/24/2016,0,17,Ait,Sidi,Karthikeyan,2,2015,3
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,0,5/15/2012,0,3,Akinkuolie,Sarah,None,2,2011,7
3,Alagbe Trina,10088,1,1,0,1,5,3,0,64991,...,0,1/3/2019,0,15,Alagbe,Trina,None,2,2008,1
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,0,2/1/2016,0,2,Anderson,Carol,None,2,2011,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,0,2/1/2016,0,2,Anderson,Carol,None,2,2011,7
578,Anderson Linda,10002,0,0,0,1,5,4,0,57568,...,0,1/7/2019,0,15,Anderson,Linda,None,3,2012,1
579,Andreola Colby,10194,0,0,0,1,4,3,0,95660,...,4,1/2/2019,0,19,Andreola,Colby,None,2,2014,11
580,Athwal Sam,10062,0,4,1,1,5,3,0,59365,...,0,2/25/2019,0,19,Athwal,Sam,None,2,2013,9
581,Bachiochi Linda,10114,0,0,0,3,5,3,1,47837,...,0,1/25/2019,0,4,Bachiochi,Linda,None,2,2009,7

In [46]:
df['Hired_Day'] = df['DateofHire'].dt.day

In [48]:
df

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,LastPerformanceReview_Date,DaysLateLast30,Absences,last_name,first_name,middle_name,PerformanceScore_ID,Hired_Year,Hired_Month,Hired_Day
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,1/17/2019,0,1,Adinolfi,Wilson,K,3,2011,7,5
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,2/24/2016,0,17,Ait,Sidi,Karthikeyan,2,2015,3,30
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,5/15/2012,0,3,Akinkuolie,Sarah,None,2,2011,7,5
3,Alagbe Trina,10088,1,1,0,1,5,3,0,64991,...,1/3/2019,0,15,Alagbe,Trina,None,2,2008,1,7
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,2/1/2016,0,2,Anderson,Carol,None,2,2011,7,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,2/1/2016,0,2,Anderson,Carol,None,2,2011,7,11
578,Anderson Linda,10002,0,0,0,1,5,4,0,57568,...,1/7/2019,0,15,Anderson,Linda,None,3,2012,1,9
579,Andreola Colby,10194,0,0,0,1,4,3,0,95660,...,1/2/2019,0,19,Andreola,Colby,None,2,2014,11,10
580,Athwal Sam,10062,0,4,1,1,5,3,0,59365,...,2/25/2019,0,19,Athwal,Sam,None,2,2013,9,30
581,Bachiochi Linda,10114,0,0,0,3,5,3,1,47837,...,1/25/2019,0,4,Bachiochi,Linda,None,2,2009,7,6

In [50]:
#Extracting name for month & day
df['Hired_Month'] = df['DateofHire'].dt.month_name()
df

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,LastPerformanceReview_Date,DaysLateLast30,Absences,last_name,first_name,middle_name,PerformanceScore_ID,Hired_Year,Hired_Month,Hired_Day
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,1/17/2019,0,1,Adinolfi,Wilson,K,3,2011,July,5
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,2/24/2016,0,17,Ait,Sidi,Karthikeyan,2,2015,March,30
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,5/15/2012,0,3,Akinkuolie,Sarah,None,2,2011,July,5
3,Alagbe Trina,10088,1,1,0,1,5,3,0,64991,...,1/3/2019,0,15,Alagbe,Trina,None,2,2008,January,7
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,2/1/2016,0,2,Anderson,Carol,None,2,2011,July,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,2/1/2016,0,2,Anderson,Carol,None,2,2011,July,11
578,Anderson Linda,10002,0,0,0,1,5,4,0,57568,...,1/7/2019,0,15,Anderson,Linda,None,3,2012,January,9
579,Andreola Colby,10194,0,0,0,1,4,3,0,95660,...,1/2/2019,0,19,Andreola,Colby,None,2,2014,November,10
580,Athwal Sam,10062,0,4,1,1,5,3,0,59365,...,2/25/2019,0,19,Athwal,Sam,None,2,2013,September,30
581,Bachiochi Linda,10114,0,0,0,3,5,3,1,47837,...,1/25/2019,0,4,Bachiochi,Linda,None,2,2009,July,6

In [54]:
df['Hired_Day_name'] = df['DateofHire'].dt.day_name()
df

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,DaysLateLast30,Absences,last_name,first_name,middle_name,PerformanceScore_ID,Hired_Year,Hired_Month,Hired_Day,Hired_Day_name
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,0,1,Adinolfi,Wilson,K,3,2011,July,5,Tuesday
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,0,17,Ait,Sidi,Karthikeyan,2,2015,March,30,Monday
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,0,3,Akinkuolie,Sarah,None,2,2011,July,5,Tuesday
3,Alagbe Trina,10088,1,1,0,1,5,3,0,64991,...,0,15,Alagbe,Trina,None,2,2008,January,7,Monday
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,0,2,Anderson,Carol,None,2,2011,July,11,Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,0,2,Anderson,Carol,None,2,2011,July,11,Monday
578,Anderson Linda,10002,0,0,0,1,5,4,0,57568,...,0,15,Anderson,Linda,None,3,2012,January,9,Monday
579,Andreola Colby,10194,0,0,0,1,4,3,0,95660,...,0,19,Andreola,Colby,None,2,2014,November,10,Monday
580,Athwal Sam,10062,0,4,1,1,5,3,0,59365,...,0,19,Athwal,Sam,None,2,2013,September,30,Monday
581,Bachiochi Linda,10114,0,0,0,3,5,3,1,47837,...,0,4,Bachiochi,Linda,None,2,2009,July,6,Monday