In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Dataset/pizza_sales.csv')
df.head()

,pizza_id,order_id,pizza_name_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name
0,1,1,hawaiian_m,1,1/1/2015,11:38:36,13.25,13.25,M,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",The Hawaiian Pizza
1,2,2,classic_dlx_m,1,1/1/2015,11:57:40,16.00,16.00,M,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",The Classic Deluxe Pizza
2,3,2,five_cheese_l,1,1/1/2015,11:57:40,18.50,18.50,L,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",The Five Cheese Pizza
3,4,2,ital_supr_l,1,1/1/2015,11:57:40,20.75,20.75,L,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza
4,5,2,mexicana_m,1,1/1/2015,11:57:40,16.00,16.00,M,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48620 entries, 0 to 48619
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   pizza_id           48620 non-null  int64
 1   order_id           48620 non-null  int64
 2   pizza_name_id      48620 non-null  object
 3   quantity           48620 non-null  int64
 4   order_date         48620 non-null  object
 5   order_time         48620 non-null  object
 6   unit_price         48620 non-null  float64
 7   total_price        48620 non-null  float64
 8   pizza_size         48620 non-null  object
 9   pizza_category     48620 non-null  object
 10  pizza_ingredients  48620 non-null  object
 11  pizza_name         48620 non-null  object
dtypes: float64(2), int64(3), object(7)
memory usage: 4.5+ MB

In [4]:
df.isnull().sum()

pizza_id             0
order_id             0
pizza_name_id        0
quantity             0
order_date           0
order_time           0
unit_price           0
total_price          0
pizza_size           0
pizza_category       0
pizza_ingredients    0
pizza_name           0
dtype: int64

In [11]:
df['order_date'] = pd.to_datetime(df['order_date'], dayfirst=True)

df['day'] = df['order_date'].dt.day_name()
df['month'] = df['order_date'].dt.month_name()

In [13]:
df['total_price'].sum()

817860.05

In [15]:
df['order_id'].nunique()

21350

In [17]:
df['quantity'].sum()

49574

In [19]:
df.groupby('order_id')['total_price'].sum().mean()

38.30726229508196

In [21]:
df.groupby('pizza_name')['quantity'].sum().sort_values(ascending=False)

pizza_name
The Classic Deluxe Pizza                      2453
The Barbecue Chicken Pizza                    2432
The Hawaiian Pizza                            2422
The Pepperoni Pizza                           2418
The Thai Chicken Pizza                        2371
The California Chicken Pizza                  2370
The Sicilian Pizza                            1938
The Spicy Italian Pizza                       1924
The Southwest Chicken Pizza                   1917
The Big Meat Pizza                            1914
The Four Cheese Pizza                         1902
The Italian Supreme Pizza                     1884
The Vegetables + Vegetables Pizza             1526
The Mexicana Pizza                            1484
The Napolitana Pizza                          1464
The Prosciutto and Arugula Pizza              1457
The Spinach and Feta Pizza                    1446
The Pepper Salami Pizza                       1446
The Italian Capocollo Pizza                   1438
The Greek Pizza                               1420
The Five Cheese Pizza                         1409
The Pepperoni, Mushroom, and Peppers Pizza    1359
The Green Garden Pizza                         997
The Chicken Alfredo Pizza                      987
The Italian Vegetables Pizza                   981
The Chicken Pesto Pizza                        973
The Spinach Pesto Pizza                        970
The Soppressata Pizza                          961
The Spinach Supreme Pizza                      950
The Calabrese Pizza                            937
The Mediterranean Pizza                        934
The Brie Carre Pizza                           490
Name: quantity, dtype: int64

In [25]:
df.groupby('pizza_name')['total_price'].sum().sort_values(ascending=False)

pizza_name
The Thai Chicken Pizza                        43434.25
The Barbecue Chicken Pizza                    42768.00
The California Chicken Pizza                  41409.50
The Classic Deluxe Pizza                      38180.50
The Spicy Italian Pizza                       34831.25
The Southwest Chicken Pizza                   34705.75
The Italian Supreme Pizza                     33476.75
The Hawaiian Pizza                            32273.25
The Four Cheese Pizza                         32265.70
The Sicilian Pizza                            30940.50
The Pepperoni Pizza                           30161.75
The Greek Pizza                               28454.10
The Mexicana Pizza                            26780.75
The Five Cheese Pizza                         26066.50
The Pepper Salami Pizza                       25529.00
The Italian Capocollo Pizza                   25094.00
The Vegetables + Vegetables Pizza             24374.75
The Prosciutto and Arugula Pizza              24193.25
The Napolitana Pizza                          24087.00
The Spinach and Feta Pizza                    23271.25
The Big Meat Pizza                            22968.00
The Pepperoni, Mushroom, and Peppers Pizza    18834.50
The Chicken Alfredo Pizza                     16900.25
The Chicken Pesto Pizza                       16701.75
The Soppressata Pizza                         16425.75
The Italian Vegetables Pizza                  16019.25
The Calabrese Pizza                           15934.25
The Spinach Pesto Pizza                       15596.00
The Mediterranean Pizza                       15360.50
The Spinach Supreme Pizza                     15277.75
The Green Garden Pizza                        13955.75
The Brie Carre Pizza                          11588.50
Name: total_price, dtype: float64

In [27]:
df.groupby('pizza_category')['total_price'].sum()

pizza_category
Chicken    195919.50
Classic    220053.10
Supreme    208197.00
Veggie     193690.45
Name: total_price, dtype: float64

In [29]:
df.groupby('pizza_size')['total_price'].sum()

pizza_size
L      375318.70
M      249382.25
S      178076.50
XL      14076.00
XXL      1006.60
Name: total_price, dtype: float64

In [38]:

df['hour'] = df['order_date'].dt.hour

df.groupby('hour')['total_price'].sum()

hour
0    817860.05
Name: total_price, dtype: float64

In [34]:
df.groupby('day')['total_price'].sum()

day
Friday       136073.90
Monday       107329.55
Saturday     123182.40
Sunday        99203.50
Thursday     123528.50
Tuesday      114133.80
Wednesday    114408.40
Name: total_price, dtype: float64

In [40]:
df.groupby('month')['total_price'].sum()

month
April        68736.80
August       68278.25
December     64701.15
February     65159.60
January      69793.30
July         72557.90
June         68230.20
March        70397.10
May          71402.75
November     70395.35
October      64027.60
September    64180.05
Name: total_price, dtype: float64

In [43]:
df['order_date'] = pd.to_datetime(df['order_date'], dayfirst=True)

df['year'] = df['order_date'].dt.year
df['month'] = df['order_date'].dt.month
df['month_name'] = df['order_date'].dt.month_name()

In [47]:
monthly_sales = (
    df.groupby(['year', 'month'])['total_price']
    .sum()
    .reset_index()
)

monthly_sales

    year  month  total_price
0   2015      1     69793.30
1   2015      2     65159.60
2   2015      3     70397.10
3   2015      4     68736.80
4   2015      5     71402.75
5   2015      6     68230.20
6   2015      7     72557.90
7   2015      8     68278.25
8   2015      9     64180.05
9   2015     10     64027.60
10  2015     11     70395.35
11  2015     12     64701.15

In [49]:
monthly_sales['MoM_Growth'] = (
    monthly_sales['total_price'].pct_change() * 100
)

monthly_sales

    year  month  total_price  MoM_Growth
0   2015      1     69793.30         NaN
1   2015      2     65159.60   -6.639176
2   2015      3     70397.10    8.037956
3   2015      4     68736.80   -2.358478
4   2015      5     71402.75    3.878490
5   2015      6     68230.20   -4.443176
6   2015      7     72557.90    6.342792
7   2015      8     68278.25   -5.898255
8   2015      9     64180.05   -6.002204
9   2015     10     64027.60   -0.237535
10  2015     11     70395.35    9.945320
11  2015     12     64701.15   -8.088887

In [51]:
monthly_sales['YoY_Growth'] = (
    monthly_sales['total_price'].pct_change(periods=12) * 100
)

monthly_sales

    year  month  total_price  MoM_Growth  YoY_Growth
0   2015      1     69793.30         NaN         NaN
1   2015      2     65159.60   -6.639176         NaN
2   2015      3     70397.10    8.037956         NaN
3   2015      4     68736.80   -2.358478         NaN
4   2015      5     71402.75    3.878490         NaN
5   2015      6     68230.20   -4.443176         NaN
6   2015      7     72557.90    6.342792         NaN
7   2015      8     68278.25   -5.898255         NaN
8   2015      9     64180.05   -6.002204         NaN
9   2015     10     64027.60   -0.237535         NaN
10  2015     11     70395.35    9.945320         NaN
11  2015     12     64701.15   -8.088887         NaN

In [53]:
latest_date = df['order_date'].max()

cmtd = df[
    (df['order_date'].dt.month == latest_date.month) &
    (df['order_date'].dt.year == latest_date.year)
]['total_price'].sum()

cmtd

64701.15

In [55]:
previous_month = latest_date.month - 1

pmtd = df[
    (df['order_date'].dt.month == previous_month) &
    (df['order_date'].dt.year == latest_date.year)
]['total_price'].sum()

pmtd

70395.35

In [57]:
cytd = df[
    df['order_date'].dt.year == latest_date.year
]['total_price'].sum()

cytd

817860.05

In [59]:
previous_year = latest_date.year - 1

pytd = df[
    df['order_date'].dt.year == previous_year
]['total_price'].sum()

pytd

0.0

In [61]:
sales_by_day = (
    df.groupby(df['order_date'].dt.day_name())['total_price']
    .sum()
    .sort_values(ascending=False)
)

sales_by_day

order_date
Friday       136073.90
Thursday     123528.50
Saturday     123182.40
Wednesday    114408.40
Tuesday      114133.80
Monday       107329.55
Sunday        99203.50
Name: total_price, dtype: float64

In [63]:
df['total_price'].sum()

817860.05

In [69]:
df.groupby('order_id')['total_price'].sum().mean()

38.30726229508196

In [71]:
df.groupby('order_id')['total_price'].sum().max()

444.2